name: Reusable Deploy to Production (Upload to temp then move)

on:
  workflow_call:
    inputs:
      build_command:
        description: '生产环境构建命令'
        required: false
        type: string
        default: 'npm run build:prod'
      target_path:
        description: '生产服务器部署路径'
        required: true
        type: string

    secrets:
      SERVER_IP:
        required: true
      SERVER_USER:
        required: true
      SERVER_SSH_KEY:
        required: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code and submodules
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: ${{ inputs.build_command }}

      - name: Upload dist to /tmp/temp-deploy via SCP
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          source: "dist/*"
          target: "/tmp/temp-deploy"

      - name: Move to production target path
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            mkdir -p ${{ inputs.target_path }}
            mv /tmp/temp-deploy/* ${{ inputs.target_path }}

      - name: Restart nginx on server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: sudo systemctl restart nginx